// src/components/materials/MaterialsGrid.tsx
import React from "react";
import MaterialCard from "./MaterialCard";

const sampleMaterials = [
  {
    id: 1,
    category: "Lumber & Panels",
    name: "2x4 SPF Stud 8ft",
    description: "Standard framing stud for walls",
    unit: "Each",
    brand: "Taiga",
    sku: "LUM-2X4-08",
    price: "$4.85",
    supplier: "Taiga",
    weight: 5.2,
    size: "96x1.5x3.5 in",
    stock: "In Stock",
    image: "http://example.com/2x4.jpg",
    notes: "KD-HT, premium grade",
  },
  {
    id: 2,
    category: "Lumber & Panels",
    name: "OSB Sheathing 4x8x7/16",
    description: "Panel for wall and roof sheathing",
    unit: "Sheet",
    brand: "West Fraser",
    sku: "OSB-716-48",
    price: "$16.5",
    supplier: "West Fraser",
    weight: 19.0,
    size: "48x96x7/16 in",
    stock: "In Stock",
    image: "http://example.com/osb.jpg",
    notes: "Exposure 1 rated",
  },
  {
    id: 3,
    category: "Concrete & Masonry",
    name: "Ready-Mix Concrete Bag 30kg",
    description: "Premixed concrete for small jobs",
    unit: "Bag",
    brand: "Quikrete",
    sku: "CON-30KG",
    price: "$7.99",
    supplier: "Home Depot",
    weight: 30.0,
    size: "30kg bag",
    stock: "In Stock",
    image: "http://example.com/concrete.jpg",
    notes: "Quick setting",
  },
  {
    id: 4,
    category: "Roofing",
    name: "Asphalt Shingle Bundle",
    description: "21 shingles per bundle",
    unit: "Bundle",
    brand: "IKO",
    sku: "ROOF-SHNG",
    price: "$29.5",
    supplier: "IKO",
    weight: 32.0,
    size: "21 pcs/bundle",
    stock: "2 Week Lead",
    image: "http://example.com/shingles.jpg",
    notes: "Architectural shingles",
  },
  {
    id: 5,
    category: "Insulation",
    name: "Fiberglass Batt Insulation R-20",
    description: "Thermal insulation for 2x6 walls",
    unit: "Bag",
    brand: "Owens Corning",
    sku: "INS-R20",
    price: "$68.0",
    supplier: "Owens Corning",
    weight: 15.0,
    size: "15.25 in x 47 in",
    stock: "In Stock",
    image: "http://example.com/insulation.jpg",
    notes: "Faced insulation batt",
  },
  {
    id: 6,
    category: "Drywall & Finishes",
    name: "Drywall 4x8x1/2",
    description: "Wallboard for interior use",
    unit: "Sheet",
    brand: "CertainTeed",
    sku: "DRY-12-48",
    price: "$15.75",
    supplier: "CertainTeed",
    weight: 23.0,
    size: "48x96x1/2 in",
    stock: "Backorder",
    image: "http://example.com/drywall.jpg",
    notes: "Fire rated option available",
  },
  {
    id: 7,
    category: "Fasteners & Adhesives",
    name: "Construction Screws 3in (1lb box)",
    description: "Box of coated screws for framing",
    unit: "Box",
    brand: "GRK",
    sku: "SCW-3IN-1LB",
    price: "$9.99",
    supplier: "GRK",
    weight: 0.45,
    size: "3 inch",
    stock: "In Stock",
    image: "http://example.com/screws.jpg",
    notes: "Coated for corrosion resistance",
  },
  {
    id: 8,
    category: "Plumbing",
    name: "PVC Pipe 3in",
    description: "PVC pipe for drainage",
    unit: "Length (ft)",
    brand: "IPEX",
    sku: "PVC-3IN",
    price: "$12.5",
    supplier: "Rona",
    weight: 4.0,
    size: "3 in diameter",
    stock: "In Stock",
    image: "http://example.com/pvc.jpg",
    notes: "CSA certified",
  },
  {
    id: 9,
    category: "Electrical",
    name: "Electrical Wire 14/2 (75m)",
    description: "Romex electrical cable for wiring",
    unit: "Roll",
    brand: "Southwire",
    sku: "ELEC-142-75M",
    price: "$89.0",
    supplier: "Southwire",
    weight: 12.0,
    size: "75m roll",
    stock: "In Stock",
    image: "http://example.com/wire.jpg",
    notes: "90°C rated",
  },
  {
    id: 10,
    category: "Doors & Windows",
    name: "Prehung Interior Door 30in",
    description: "Interior hollow core door with frame",
    unit: "Each",
    brand: "Masonite",
    sku: "DOOR-INT-30",
    price: "$179.0",
    supplier: "Allmar",
    weight: 35.0,
    size: "30 in x 80 in",
    stock: "Special Order",
    image: "http://example.com/door.jpg",
    notes: "Hollow core",
  },
  {
    id: 11,
    category: "Paint & Coatings",
    name: "Exterior Primer 3.78L",
    description: "Primer for exterior surfaces",
    unit: "Can",
    brand: "Benjamin Moore",
    sku: "PAINT-PRM-EXT",
    price: "$49.99",
    supplier: "Benjamin Moore",
    weight: 5.0,
    size: "3.78L can",
    stock: "In Stock",
    image: "http://example.com/primer.jpg",
    notes: "Weather resistant",
  },
  {
    id: 12,
    category: "Equipment",
    name: "Portable Generator 5000W",
    description: "Gas powered portable generator",
    unit: "Each",
    brand: "Honda",
    sku: "GEN-5000W",
    price: "$950.0",
    supplier: "Home Depot",
    weight: 95.0,
    size: "24x18x20 in",
    stock: "In Stock",
    image: "http://example.com/generator.jpg",
    notes: "Runs 8 hours on 50% load",
  },
  {
    id: 13,
    category: "Hand Tools",
    name: "Claw Hammer 16oz",
    description: "Steel hammer with grip",
    unit: "Each",
    brand: "Stanley",
    sku: "TOOL-HAM-16",
    price: "$19.99",
    supplier: "Stanley",
    weight: 0.45,
    size: "16 oz",
    stock: "In Stock",
    image: "http://example.com/hammer.jpg",
    notes: "Fiberglass handle",
  },
  {
    id: 14,
    category: "Power Tools",
    name: "Cordless Drill 20V",
    description: "Battery drill with charger",
    unit: "Each",
    brand: "DeWalt",
    sku: "POW-DRV-20V",
    price: "$149.99",
    supplier: "DeWalt",
    weight: 2.0,
    size: "7.5 in length",
    stock: "In Stock",
    image: "http://example.com/drill.jpg",
    notes: "Includes 2 batteries",
  },
  {
    id: 15,
    category: "Safety Gear",
    name: "Hard Hat CSA Approved",
    description: "CSA approved safety helmet",
    unit: "Each",
    brand: "3M",
    sku: "SAFE-HH-CSA",
    price: "$14.99",
    supplier: "3M",
    weight: 0.35,
    size: "Universal size",
    stock: "In Stock",
    image: "http://example.com/hardhat.jpg",
    notes: "ANSI/CSA compliant",
  },
];

const MaterialsGrid: React.FC = () => {
  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
      {sampleMaterials.map((mat) => (
        <MaterialCard
          key={mat.id}
          name={mat.name}
          size={mat.size}
          unit={mat.unit}
          price={mat.price}
          vendors={[mat.supplier]}
          image={mat.image} // 👈 pass image here
        />
      ))}
    </div>
  );
};

export default MaterialsGrid;
